import type {Metadata} from "next";
import "./../css/globals.css";
import Header from "@/components/Header/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className='w-screen w-max-[1440px] min-h-screen h-full flex flex-col mx-auto px-6 bg-background_auth bg-center bg-no-repeat bg-cover'
    >
    <Header/>
    {children}
    </body>
    </html>
  );
}
